import { FormEvent, useCallback, useEffect, useState } from "react";

import { api, formatDate } from "./client";
import type { Language } from "./client";

export type AuthUser = { id: string; email: string; display_name: string; status: string };
export type AuthStatus = { enabled: boolean; bootstrap_required: boolean; user: AuthUser | null; zero_cost: boolean };
type Member = { user_id: string; display_name: string; email: string; role: string };
type Team = { id: string; name: string; slug: string; role: string; members: Member[] };
type SecurityEvent = { id: string; event_type: string; actor_user_id: string | null; team_id: string | null; payload: Record<string, unknown>; created_at: string };

const copy = {
  "zh-CN": {
    title: "账户与团队", disabled: "当前是免登录单机模式。需要多人共享时，在本机 .env 中启用 GAMECRAFTER_AUTH_ENABLED=true 并重启。",
    safe: "账户、密码哈希、会话、邀请与权限都只保存在你的数据库中，不依赖付费身份服务。",
    setup: "创建本机所有者", login: "登录", name: "显示名称", email: "邮箱", password: "密码（至少 12 位）", submit: "继续", logout: "退出登录",
    invitedRegister: "我是受邀新成员", backLogin: "返回登录",
    teams: "我的团队", createTeam: "新建团队", teamName: "团队名称", invite: "邀请成员", inviteEmail: "成员邮箱", role: "角色", token: "一次性邀请令牌（请安全发送给对方）",
    accept: "接受邀请", acceptToken: "粘贴邀请令牌", revoke: "撤销成员", owner: "所有者", editor: "编辑", reviewer: "审核", viewer: "只读", working: "处理中…",
    data: "项目数据", export: "导出完整可移植 ZIP", delete: "永久删除项目", deleteHint: "先导出备份。删除会移除数据库记录及不再被引用的私有文件，无法撤销。", confirm: "输入确认文字",
    deleteAccount: "删除本机账户", accountHint: "必须先删除或转移自己拥有的项目与团队。此操作不可撤销。",
    audit: "安全审计记录",
  },
  en: {
    title: "Account & teams", disabled: "This installation is in passwordless single-machine mode. Enable GAMECRAFTER_AUTH_ENABLED=true in the local .env and restart before sharing it.",
    safe: "Accounts, password hashes, sessions, invitations, and permissions remain in your database with no paid identity service.",
    setup: "Create local owner", login: "Sign in", name: "Display name", email: "Email", password: "Password (12+ characters)", submit: "Continue", logout: "Sign out",
    invitedRegister: "I am a newly invited member", backLogin: "Back to sign in",
    teams: "My teams", createTeam: "Create team", teamName: "Team name", invite: "Invite member", inviteEmail: "Member email", role: "Role", token: "One-time invitation token (send securely)",
    accept: "Accept invitation", acceptToken: "Paste invitation token", revoke: "Revoke member", owner: "Owner", editor: "Editor", reviewer: "Reviewer", viewer: "Read only", working: "Working…",
    data: "Project data", export: "Export complete portable ZIP", delete: "Permanently delete project", deleteHint: "Export a backup first. Deletion removes database records and unreferenced private files and cannot be undone.", confirm: "Type the confirmation",
    deleteAccount: "Delete local account", accountHint: "Delete or transfer every owned project and team first. This cannot be undone.",
    audit: "Security audit trail",
  },
} as const;

export function AccountWorkspace({ status, language, gate = false, onChanged, project }: { status: AuthStatus; language: Language; gate?: boolean; onChanged: () => Promise<void>; project?: { id: string; slug: string } | null }) {
  const t = copy[language]; const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [teams, setTeams] = useState<Team[]>([]);
  const [teamName, setTeamName] = useState(""); const [teamId, setTeamId] = useState(""); const [inviteEmail, setInviteEmail] = useState(""); const [inviteRole, setInviteRole] = useState<"editor" | "reviewer" | "viewer">("reviewer"); const [acceptToken, setAcceptToken] = useState(""); const [issuedToken, setIssuedToken] = useState("");
  const [securityEvents, setSecurityEvents] = useState<SecurityEvent[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [registering, setRegistering] = useState(false); const [registrationToken, setRegistrationToken] = useState("");
  const [deleteConfirmation, setDeleteConfirmation] = useState("");
  const [accountConfirmation, setAccountConfirmation] = useState("");
  const load = useCallback(async () => { if (!status.user) return; const [payload, auditPayload] = await Promise.all([api<{ user: AuthUser; teams: Team[] }>("/api/auth/me"), api<{ items: SecurityEvent[] }>("/api/auth/security-events")]); setTeams(payload.teams); setSecurityEvents(auditPayload.items); setTeamId((current) => current || payload.teams[0]?.id || ""); }, [status.user]);
  useEffect(() => { void load().catch((reason) => setError(String(reason))); }, [load]);
  const authenticate = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const path = status.bootstrap_required ? "/api/auth/bootstrap" : registering ? "/api/auth/register" : "/api/auth/login"; const body = status.bootstrap_required ? { email, password, display_name: name } : registering ? { email, password, display_name: name, invitation_token: registrationToken } : { email, password }; await api(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const deleteProject = async () => { if (!project) return; setBusy(true); try { await api(`/api/projects/${project.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: deleteConfirmation }) }); setDeleteConfirmation(""); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const dataPanel = project ? <section className="panel"><h2>{t.data}</h2><p>{t.deleteHint}</p><a className="secondary-button" href={`/api/projects/${project.id}/portable-export`} download>{t.export}</a><label><span>{t.confirm}: DELETE {project.slug}</span><input value={deleteConfirmation} onChange={(event) => setDeleteConfirmation(event.target.value)} /></label><button type="button" disabled={busy || deleteConfirmation !== `DELETE ${project.slug}`} onClick={() => void deleteProject()}>{t.delete}</button></section> : null;
  if (!status.enabled) return <div className="knowledge-workspace"><section className="panel"><div className="panel-heading"><span>00</span><div><h2>{t.title}</h2><p>{t.disabled}</p></div></div><p>{t.safe}</p></section>{dataPanel}</div>;
  if (!status.user) return <section className={gate ? "center-state account-gate" : "panel"}><h1>{status.bootstrap_required ? t.setup : registering ? t.invitedRegister : t.login}</h1><p>{t.safe}</p>{error && <div className="notice notice--error">{error}</div>}<form className="form-grid" onSubmit={authenticate}>{(status.bootstrap_required || registering) && <label><span>{t.name}</span><input required value={name} onChange={(event) => setName(event.target.value)} /></label>}<label><span>{t.email}</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label><span>{t.password}</span><input required minLength={12} type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{registering && <label><span>{t.acceptToken}</span><input required value={registrationToken} onChange={(event) => setRegistrationToken(event.target.value)} /></label>}<button className="primary-button" disabled={busy} type="submit">{busy ? t.working : t.submit}</button></form>{!status.bootstrap_required && <button type="button" onClick={() => setRegistering((value) => !value)}>{registering ? t.backLogin : t.invitedRegister}</button>}</section>;
  const createTeam = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api("/api/auth/teams", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: teamName }) }); setTeamName(""); await load(); } finally { setBusy(false); } };
  const invite = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { const result = await api<{ acceptance_token: string }>(`/api/auth/teams/${teamId}/invitations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: inviteEmail, role: inviteRole }) }); setIssuedToken(result.acceptance_token); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const accept = async (event: FormEvent) => { event.preventDefault(); setBusy(true); try { await api("/api/auth/invitations/accept", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: acceptToken }) }); setAcceptToken(""); await load(); } finally { setBusy(false); } };
  const revoke = async (team: Team, member: Member) => { setBusy(true); try { await api(`/api/auth/teams/${team.id}/members/${member.user_id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const logout = async () => { await api("/api/auth/logout", { method: "POST" }); await onChanged(); };
  const deleteAccount = async () => { setBusy(true); try { await api("/api/auth/me", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: accountConfirmation }) }); await onChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const accountDeletePanel = <section className="panel"><h2>{t.deleteAccount}</h2><p>{t.accountHint}</p><label><span>{t.confirm}: DELETE {status.user.email}</span><input value={accountConfirmation} onChange={(event) => setAccountConfirmation(event.target.value)} /></label><button type="button" disabled={busy || accountConfirmation !== `DELETE ${status.user.email}`} onClick={() => void deleteAccount()}>{t.deleteAccount}</button></section>;
  return <div className="knowledge-workspace"><section className="panel"><div className="list-heading"><div><h2>{status.user.display_name}</h2><p>{status.user.email}</p></div><button type="button" onClick={() => void logout()}>{t.logout}</button></div><p>{t.safe}</p></section>{error && <div className="notice notice--error">{error}</div>}{dataPanel}<section className="panel"><div className="list-heading"><h2>{t.teams}</h2><span>{teams.length}</span></div><form className="form-grid" onSubmit={createTeam}><label><span>{t.teamName}</span><input required value={teamName} onChange={(event) => setTeamName(event.target.value)} /></label><button type="submit" disabled={busy}>{t.createTeam}</button></form>{teams.map((team) => <article className="source-card" key={team.id}><div><h3>{team.name}</h3><small>{team.role}</small>{team.members.map((member) => <div className="list-heading" key={member.user_id}><p>{member.display_name} · {member.email} · {member.role}</p>{team.role === "owner" && member.role !== "owner" && <button type="button" disabled={busy} onClick={() => void revoke(team, member)}>{t.revoke}</button>}</div>)}</div></article>)}</section><section className="panel"><h2>{t.invite}</h2><form className="form-grid" onSubmit={invite}><label><span>{t.teams}</span><select value={teamId} onChange={(event) => setTeamId(event.target.value)}>{teams.filter((team) => team.role === "owner").map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label><span>{t.inviteEmail}</span><input required type="email" value={inviteEmail} onChange={(event) => setInviteEmail(event.target.value)} /></label><label><span>{t.role}</span><select value={inviteRole} onChange={(event) => setInviteRole(event.target.value as typeof inviteRole)}><option value="editor">{t.editor}</option><option value="reviewer">{t.reviewer}</option><option value="viewer">{t.viewer}</option></select></label><button disabled={busy || !teamId} type="submit">{t.invite}</button></form>{issuedToken && <label><span>{t.token}</span><textarea readOnly value={issuedToken} /></label>}<form className="form-grid" onSubmit={accept}><label><span>{t.acceptToken}</span><input required value={acceptToken} onChange={(event) => setAcceptToken(event.target.value)} /></label><button disabled={busy} type="submit">{t.accept}</button></form></section><section className="panel"><div className="list-heading"><h2>{t.audit}</h2><span>{securityEvents.length}</span></div>{securityEvents.map((item) => <article className="source-card" key={item.id}><strong>{item.event_type}</strong><small>{formatDate(item.created_at, language)}</small></article>)}</section>{accountDeletePanel}</div>;
}
